dist: bionic

arch:
  - amd64
  - ppc64le
  - arm64

os: linux

language: python
python:
    - 3.8

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -y graphviz python3-matplotlib python3-sklearn python3-pandas python3-scipy python3-numpy python3-sqlalchemy ipython3  python3-pydot python3-nbconvert

cache:
directories:
- $HOME/.cache/matplotlib

install:
    # removed all these. replaced by equivalent debian packages  
    # pip install scipy pandas sklearn matplotlib pydot dill sqlalchemy jupyter xgboost ipython
    # 

script: 
    - export PYTHONPATH=$PYTHONPATH:..
    - df
    - free
    - cat /proc/cpuinfo
    - mkdir -p logs
    - rm -rf ~/.matplotlib
    - rm -rf ~/.cache/matplotlib
    - rm -rf ~/.matplotlib/fontList.cache  
    - fc-cache 
    - python ./tests/bugs/issue_36/display_version_info.py
    - python tests/demos/demo1.py
    - python tests/func/test_ozone.py
    - python tests/func/test_air_passengers.py
    - make PYTHON=python -f tests/Makefile build-test
    - python scripts/upload_to_chunk.io.py
    - pip install .
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute docs/sample_code.ipynb
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute docs/PyAF_Introduction.ipynb
    - jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=None --execute docs/PyAF_Exogenous.ipynb
    
